server:
  port: 8885

#在同级目录下生成log文件夹
logging:
  path: logs
  file: mylog.log
spring:
  application:
    name: myTest
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC
    username: root
    password: pengfei6993
mybatis:
  type-aliases-package: com.course.model
  mapper-locations:
    - mapper/*
